### ISSUE TITLE
Ask search.gov about -er stems for search results

### ISSUE THREAD

**Issue by brandocalrissian** [18F/cv_faq#840]
## Description
- _What is the problem we're trying to solve?_
High-er and low-er

- _What problem does this issue address for the public?_

- _How does this issue address the problem?_

- _How will we know that the problem is resolved?_

## Notes
Examples of "er" problem as of 6/30

- fast/faster: search for fast returns 0 results but faster returns 2.
- high/higher: search for high returns 10 results but higher returns 19. 2 of 19 "higher" results are included in the "high" results - " What about underlying medical conditions that are not included on this list?" and " While school's out, should I limit time with older adults, including relatives, and people with chronic medical conditions? "
- late/later: search for late returns 0 results but later returns 3.
- low/lower: search for low returns 11 results but lower returns 3. None of the 3 "lower" results is included in the "low" results.
- poor/poorer: search for poor returns 0 results but poorer returns 2.
- big/bigger: search for big returns 0 results but bigger returns 1.
- up/upper: search for up returns 19 but upper returns 3. None of the 3 "upper" results is included in the "up" results.

## Acceptance Criteria
- [ ]

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by debjudy** [comment]
Since Dawn out this week on vacation, sent email to support team.   The following represent examples of the problem 

- fast/faster: search for fast returns 0 results but faster returns 2.
- high/higher: search for high returns 10 results but higher returns 19. 2 of 19 "higher" results are included in the "high" results - " What about underlying medical conditions that are not included on this list?" and " While school's out, should I limit time with older adults, including relatives, and people with chronic medical conditions? "
- late/later: search for late returns 0 results but later returns 3.
- low/lower: search for low returns 11 results but lower returns 3. None of the 3 "lower" results is included in the "low" results.
- poor/poorer: search for poor returns 0 results but poorer returns 2.
- big/bigger: search for big returns 0 results but bigger returns 1.
- up/upper: search for up returns 19 but upper returns 3. None of the 3 "upper" results is included in the "up" results.

**Comment by debjudy** [comment]
From Dawn @ search.gov
Dawn (TTS Solutions Support)Jul 8, 2020, 7:17 AM EDT
Hi Deb, following up on our Slack conversation, we'll need to have a dev investigate why the stemmer isn't handling the more common `er` endings. My gut indicates it might be excluded from the stemmer due to so many words legitimately ending in `er` which should not be stemmed, but we'll need to confirm, and see if there's a way we can find a both/and solution to the issue you flagged.

**Comment by debjudy** [comment]
Closing this ticket as this issue has been added to the search.gov backlog and the number of searches impacting on our site is small.  

Dawn (TTS Solutions Support)Jul 8, 2020, 10:42 AM EDT 
I'll make sure this is noted in our planning docs for improving language handling. 

Impact on FAQ
The high/higher pair is where we noticed the behavior. (Searches for high risk or higher risk for covid-19.) The others are examples to see if the behavior was consistent. The search volume, though, for high/higher is tiny less than 1% of overall
searches, so overall impact to users is very low. For our specific scenario, we are working on implementing Best Bets to
improve the search response for high/higher.
